repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check
        language: system
        entry: npx biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
        types_or: [javascript, jsx, ts, tsx, json]
        files: ^frontend/
        pass_filenames: false
