"""PSLmodels Tax-Calculator cross-validation tests.

Compares locally loaded tax data (IRS-sourced) against a committed snapshot of
PSLmodels Tax-Calculator's policy_current_law.json. This provides an automated
second-opinion check — if PSLmodels and our data disagree, either we have a typo
or PSLmodels hasn't adopted a recent IRS change (e.g., OBBB Act).

The snapshot file is generated by:
    uv run python scripts/fetch_pslmodels_data.py snapshot --years 2025 2026

No network access at test time — reads from committed snapshot only.

PSLmodels source:
    https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/policy_current_law.json
"""

from __future__ import annotations

import json
from decimal import Decimal
from pathlib import Path
from typing import Any

import pytest

from taxtracker.models.tax_data import FilingStatus
from taxtracker.services.data_loader import (
    get_available_years,
    load_fica_limits_model,
    load_tax_brackets_model,
)

pytestmark = pytest.mark.unit

# ---------------------------------------------------------------------------
# Snapshot loading
# ---------------------------------------------------------------------------

SNAPSHOT_PATH = Path(__file__).resolve().parent.parent / "data" / "pslmodels_snapshot.json"

# Known divergences between PSLmodels and IRS-published values.
# Key: (year, category, detail) -> explanation string.
# When PSLmodels hasn't adopted a recent IRS change, document it here so the
# test skips that assertion instead of failing.
#
# Example:
#   ("2025", "standard_deductions", "single"): "PSLmodels uses pre-OBBB value $14,600"
KNOWN_DIVERGENCES: dict[tuple[str, str, str], str] = {}


def _load_snapshot() -> dict[str, Any] | None:
    """Load snapshot file, returning None if missing."""
    if not SNAPSHOT_PATH.exists():
        return None
    with SNAPSHOT_PATH.open() as f:
        data: dict[str, Any] = json.load(f)
    return data


def _snapshot_years() -> list[str]:
    """Return list of years in the snapshot that also exist in local data."""
    snap = _load_snapshot()
    if snap is None:
        return []
    available = {str(y) for y in get_available_years()}
    return sorted(y for y in snap.get("years", {}) if y in available)


def _skip_if_divergence(year: str, category: str, detail: str) -> None:
    """Skip test if this specific value has a known divergence."""
    key = (year, category, detail)
    if key in KNOWN_DIVERGENCES:
        pytest.skip(f"Known divergence: {KNOWN_DIVERGENCES[key]}")


# Parametrize helpers
SNAPSHOT_YEARS = _snapshot_years()
FILING_STATUSES = [
    "single",
    "married_filing_jointly",
    "married_filing_separately",
    "head_of_household",
]
BRACKET_INDICES = list(range(6))  # 6 thresholds (brackets 0-5, bracket 6 has no threshold)


def _needs_snapshot(years: list[str]) -> pytest.MarkDecorator:
    """Return skipif marker when snapshot has no years."""
    return pytest.mark.skipif(
        len(years) == 0,
        reason="PSLmodels snapshot not found or covers no local years",
    )


# ---------------------------------------------------------------------------
# Tax Bracket Thresholds
# ---------------------------------------------------------------------------


@_needs_snapshot(SNAPSHOT_YEARS)
class TestPSLmodelsBrackets:
    """Cross-check bracket thresholds against PSLmodels snapshot."""

    @pytest.fixture(autouse=True)
    def _load_data(self) -> None:
        self.snapshot = _load_snapshot()
        assert self.snapshot is not None

    @pytest.mark.parametrize("year", SNAPSHOT_YEARS)
    @pytest.mark.parametrize("status", FILING_STATUSES)
    @pytest.mark.parametrize("bracket_idx", BRACKET_INDICES)
    def test_bracket_threshold(self, year: str, status: str, bracket_idx: int) -> None:
        """Bracket {bracket_idx} threshold for {status} in {year} matches PSLmodels."""
        _skip_if_divergence(year, "bracket_threshold", f"{status}_{bracket_idx}")

        psl_year = self.snapshot["years"][year]
        psl_brackets = psl_year["tax_brackets"][status]
        psl_threshold = psl_brackets[bracket_idx]["threshold"]

        local = load_tax_brackets_model(int(year))
        local_brackets = local.tax_brackets[FilingStatus(status)]
        local_threshold = local_brackets[bracket_idx].threshold

        if psl_threshold is None:
            assert local_threshold is None, (
                f"PSLmodels has no threshold for bracket {bracket_idx} "
                f"but local has {local_threshold}"
            )
        else:
            assert local_threshold == Decimal(str(int(psl_threshold))), (
                f"Bracket {bracket_idx} ({status}, {year}): "
                f"local={local_threshold}, PSLmodels={psl_threshold}"
            )


# ---------------------------------------------------------------------------
# Tax Rates
# ---------------------------------------------------------------------------


@_needs_snapshot(SNAPSHOT_YEARS)
class TestPSLmodelsRates:
    """Cross-check income tax rates against PSLmodels snapshot."""

    @pytest.fixture(autouse=True)
    def _load_data(self) -> None:
        self.snapshot = _load_snapshot()
        assert self.snapshot is not None

    @pytest.mark.parametrize("year", SNAPSHOT_YEARS)
    @pytest.mark.parametrize("rate_idx", list(range(7)))
    def test_rate(self, year: str, rate_idx: int) -> None:
        """Tax rate {rate_idx} in {year} matches PSLmodels."""
        _skip_if_divergence(year, "tax_rate", str(rate_idx))

        psl_rate = self.snapshot["years"][year]["tax_rates"][rate_idx]

        local = load_tax_brackets_model(int(year))
        # Rates are the same across all statuses; check against single
        local_rate = local.tax_brackets[FilingStatus.SINGLE][rate_idx].rate

        assert local_rate == Decimal(str(psl_rate)), (
            f"Rate {rate_idx} ({year}): local={local_rate}, PSLmodels={psl_rate}"
        )


# ---------------------------------------------------------------------------
# Standard Deductions
# ---------------------------------------------------------------------------


@_needs_snapshot(SNAPSHOT_YEARS)
class TestPSLmodelsStandardDeductions:
    """Cross-check standard deduction amounts against PSLmodels snapshot."""

    @pytest.fixture(autouse=True)
    def _load_data(self) -> None:
        self.snapshot = _load_snapshot()
        assert self.snapshot is not None

    @pytest.mark.parametrize("year", SNAPSHOT_YEARS)
    @pytest.mark.parametrize("status", FILING_STATUSES)
    def test_standard_deduction(self, year: str, status: str) -> None:
        """Standard deduction for {status} in {year} matches PSLmodels."""
        _skip_if_divergence(year, "standard_deductions", status)

        psl_amount = self.snapshot["years"][year]["standard_deductions"][status]

        local = load_tax_brackets_model(int(year))
        local_amount = local.standard_deductions.amounts[FilingStatus(status)]

        assert local_amount == Decimal(str(psl_amount)), (
            f"Standard deduction ({status}, {year}): local={local_amount}, PSLmodels={psl_amount}"
        )


# ---------------------------------------------------------------------------
# Aged Additional Deductions
# ---------------------------------------------------------------------------


@_needs_snapshot(SNAPSHOT_YEARS)
class TestPSLmodelsAgedDeductions:
    """Cross-check age 65+ additional deduction against PSLmodels snapshot."""

    @pytest.fixture(autouse=True)
    def _load_data(self) -> None:
        self.snapshot = _load_snapshot()
        assert self.snapshot is not None

    @pytest.mark.parametrize("year", SNAPSHOT_YEARS)
    @pytest.mark.parametrize("aged_key", ["single", "married"])
    def test_aged_deduction(self, year: str, aged_key: str) -> None:
        """Age 65+ deduction for {aged_key} in {year} matches PSLmodels."""
        _skip_if_divergence(year, "aged_deductions", aged_key)

        psl_amount = self.snapshot["years"][year]["aged_deductions"][aged_key]

        local = load_tax_brackets_model(int(year))
        local_amount = local.standard_deductions.additional_age_65_plus[aged_key]

        assert local_amount == Decimal(str(psl_amount)), (
            f"Aged deduction ({aged_key}, {year}): local={local_amount}, PSLmodels={psl_amount}"
        )


# ---------------------------------------------------------------------------
# FICA — Social Security
# ---------------------------------------------------------------------------


@_needs_snapshot(SNAPSHOT_YEARS)
class TestPSLmodelsFICA:
    """Cross-check FICA parameters against PSLmodels snapshot."""

    @pytest.fixture(autouse=True)
    def _load_data(self) -> None:
        self.snapshot = _load_snapshot()
        assert self.snapshot is not None

    @pytest.mark.parametrize("year", SNAPSHOT_YEARS)
    def test_ss_wage_base(self, year: str) -> None:
        """SS wage base in {year} matches PSLmodels."""
        _skip_if_divergence(year, "fica", "ss_wage_base")

        psl_ss = self.snapshot["years"][year]["fica"]["social_security"]
        psl_wage_base = psl_ss["wage_base_limit"]

        local = load_fica_limits_model(int(year))
        assert local.social_security.wage_base_limit == Decimal(str(psl_wage_base)), (
            f"SS wage base ({year}): "
            f"local={local.social_security.wage_base_limit}, PSLmodels={psl_wage_base}"
        )

    @pytest.mark.parametrize("year", SNAPSHOT_YEARS)
    def test_ss_employee_rate(self, year: str) -> None:
        """SS employee rate in {year} matches PSLmodels."""
        _skip_if_divergence(year, "fica", "ss_employee_rate")

        psl_rate = self.snapshot["years"][year]["fica"]["social_security"]["employee_rate"]

        local = load_fica_limits_model(int(year))
        assert local.social_security.employee_rate == Decimal(str(psl_rate)), (
            f"SS employee rate ({year}): "
            f"local={local.social_security.employee_rate}, PSLmodels={psl_rate}"
        )

    @pytest.mark.parametrize("year", SNAPSHOT_YEARS)
    def test_medicare_employee_rate(self, year: str) -> None:
        """Medicare employee rate in {year} matches PSLmodels."""
        _skip_if_divergence(year, "fica", "medicare_employee_rate")

        psl_rate = self.snapshot["years"][year]["fica"]["medicare"]["employee_rate"]

        local = load_fica_limits_model(int(year))
        assert local.medicare.employee_rate == Decimal(str(psl_rate)), (
            f"Medicare employee rate ({year}): "
            f"local={local.medicare.employee_rate}, PSLmodels={psl_rate}"
        )

    @pytest.mark.parametrize("year", SNAPSHOT_YEARS)
    def test_ss_max_employee_tax(self, year: str) -> None:
        """SS max employee tax in {year} matches PSLmodels."""
        _skip_if_divergence(year, "fica", "ss_max_employee_tax")

        psl_max = self.snapshot["years"][year]["fica"]["social_security"]["max_employee_tax"]

        local = load_fica_limits_model(int(year))
        assert local.social_security.max_employee_tax == Decimal(str(psl_max)), (
            f"SS max employee tax ({year}): "
            f"local={local.social_security.max_employee_tax}, PSLmodels={psl_max}"
        )


# ---------------------------------------------------------------------------
# Additional Medicare Tax
# ---------------------------------------------------------------------------


@_needs_snapshot(SNAPSHOT_YEARS)
class TestPSLmodelsAdditionalMedicare:
    """Cross-check Additional Medicare Tax against PSLmodels snapshot."""

    @pytest.fixture(autouse=True)
    def _load_data(self) -> None:
        self.snapshot = _load_snapshot()
        assert self.snapshot is not None

    @pytest.mark.parametrize("year", SNAPSHOT_YEARS)
    def test_additional_medicare_rate(self, year: str) -> None:
        """Additional Medicare rate in {year} matches PSLmodels."""
        _skip_if_divergence(year, "additional_medicare", "rate")

        psl_rate = self.snapshot["years"][year]["fica"]["additional_medicare"]["rate"]

        local = load_fica_limits_model(int(year))
        assert local.additional_medicare.rate == Decimal(str(psl_rate)), (
            f"Additional Medicare rate ({year}): "
            f"local={local.additional_medicare.rate}, PSLmodels={psl_rate}"
        )

    @pytest.mark.parametrize("year", SNAPSHOT_YEARS)
    @pytest.mark.parametrize("status", FILING_STATUSES)
    def test_additional_medicare_threshold(self, year: str, status: str) -> None:
        """Additional Medicare threshold for {status} in {year} matches PSLmodels."""
        _skip_if_divergence(year, "additional_medicare", f"threshold_{status}")

        psl_thresholds = self.snapshot["years"][year]["fica"]["additional_medicare"]["thresholds"]
        psl_threshold = psl_thresholds[status]

        local = load_fica_limits_model(int(year))
        local_threshold = local.additional_medicare.thresholds[status]

        assert local_threshold == Decimal(str(psl_threshold)), (
            f"Additional Medicare threshold ({status}, {year}): "
            f"local={local_threshold}, PSLmodels={psl_threshold}"
        )


# ---------------------------------------------------------------------------
# Child Tax Credit
# ---------------------------------------------------------------------------


@_needs_snapshot(SNAPSHOT_YEARS)
class TestPSLmodelsCTC:
    """Cross-check Child Tax Credit against PSLmodels snapshot."""

    @pytest.fixture(autouse=True)
    def _load_data(self) -> None:
        self.snapshot = _load_snapshot()
        assert self.snapshot is not None

    @pytest.mark.parametrize("year", SNAPSHOT_YEARS)
    def test_ctc_amount_per_child(self, year: str) -> None:
        """CTC amount per child in {year} matches PSLmodels."""
        _skip_if_divergence(year, "ctc", "amount_per_child")

        psl_amount = self.snapshot["years"][year]["child_tax_credit"]["amount_per_child"]

        local = load_tax_brackets_model(int(year))
        assert local.child_tax_credit.amount_per_child == Decimal(str(psl_amount)), (
            f"CTC amount ({year}): "
            f"local={local.child_tax_credit.amount_per_child}, PSLmodels={psl_amount}"
        )

    @pytest.mark.parametrize("year", SNAPSHOT_YEARS)
    def test_ctc_refundable_portion(self, year: str) -> None:
        """CTC refundable portion in {year} matches PSLmodels."""
        _skip_if_divergence(year, "ctc", "refundable_portion")

        psl_refund = self.snapshot["years"][year]["child_tax_credit"]["refundable_portion"]

        local = load_tax_brackets_model(int(year))
        assert local.child_tax_credit.refundable_portion == Decimal(str(psl_refund)), (
            f"CTC refundable ({year}): "
            f"local={local.child_tax_credit.refundable_portion}, PSLmodels={psl_refund}"
        )

    @pytest.mark.parametrize("year", SNAPSHOT_YEARS)
    @pytest.mark.parametrize("status", FILING_STATUSES)
    def test_ctc_phase_out_threshold(self, year: str, status: str) -> None:
        """CTC phase-out for {status} in {year} matches PSLmodels."""
        _skip_if_divergence(year, "ctc", f"phase_out_{status}")

        psl_threshold = self.snapshot["years"][year]["child_tax_credit"]["phase_out_threshold"][
            status
        ]

        local = load_tax_brackets_model(int(year))
        local_threshold = local.child_tax_credit.phase_out_threshold[FilingStatus(status)]

        assert local_threshold == Decimal(str(psl_threshold)), (
            f"CTC phase-out ({status}, {year}): local={local_threshold}, PSLmodels={psl_threshold}"
        )
